// Top-level build.gradle
buildscript {
    ext {
        compose_version = '1.6.5'
        navigation_version = '2.7.7'
        coil_version = '2.5.0'
        lifecycle_version = '2.7.0'
        retrofit_version = '2.9.0'
        room_version = '2.6.1'
        jsoup_version = '1.17.0'
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

plugins {
    id 'com.android.application' version '8.9.1' apply false
    id 'com.android.library' version '8.9.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.23' apply false
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
